server:
  port: 8081

  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30

  servlet:
    context-path: /admin

spring:
#  数据库配置
  datasource:
    name: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123123
#  页面配置
  mvc:
    view:
      suffix: .html
      prefix: templates/
    static-path-pattern: /static/**
    thymeleaf:
      prefix: classpath:/templates/

# 日志配置
logging:
  level:
    com: debug

# mybaits配置路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.ssmdemo.pojo.model

# jwt配置
jwt:
  header: Authorization
  base64-secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  token-validity-in-seconds: 14400000
