server:
  port: 8081

  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30

  servlet:
    context-path: /admin

spring:
#  数据库配置
  datasource:
    name: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123123
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 10000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: test
      auto-commit: true
      connection-test-query: SELECT 1
      connection-init-sql: SET NAMES utf8mb4
  #  页面配置
  mvc:
    view:
      suffix: .html
      prefix: templates/
    static-path-pattern: /static/**
    thymeleaf:
      prefix: classpath:/templates/

# 日志配置
logging:
  level:
    com: debug

# mybaits配置路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.ssmdemo.module.sys.pojo.model

# jwt配置
jwt:
  header: X-Token
  base64-secret: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
  token-validity-in-seconds: 14400000
